Fixed Makefile dependencies and linked libraries
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/v5_5_0@827 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/backends/cdb/configure b/backends/cdb/configure
--- a/backends/cdb/configure
+++ b/backends/cdb/configure
@@ -2874,8 +2874,8 @@ echo $ECHO_N "checking for vpopmail build... $ECHO_C" >&6; }
 if ! test -r ../module.mk; then
    { echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6; }
-   { { echo "$as_me:$LINENO: error: vpopmail is not built -- please build the vpopmail source before trying to build modules" >&5
-echo "$as_me: error: vpopmail is not built -- please build the vpopmail source before trying to build modules" >&2;}
+   { { echo "$as_me:$LINENO: error: vpopmail is not compiled -- please build the vpopmail source before trying to build modules" >&5
+echo "$as_me: error: vpopmail is not compiled -- please build the vpopmail source before trying to build modules" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
