Added check if crypt() supports MD5
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/v5_5_0@820 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7276,6 +7276,87 @@ cat >>confdefs.h <<_ACEOF
 #define MD5_PASSWORDS $ENABLE_MD5_PASSWORDS
 _ACEOF
 
+
+	  { echo "$as_me:$LINENO: checking whether system supports MD5 passwords" >&5
+echo $ECHO_N "checking whether system supports MD5 passwords... $ECHO_C" >&6; }
+	  if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		 #include <stdio.h>
+	     #include <string.h>
+	     #include <unistd.h>
+
+	     int main(int argc, char *argv[])
+	     {
+	  	  char *ret = NULL;
+	  	  const char salt[12] = "\$1\$ABCDEFG\0", key[5] = "test\0";
+
+	  	  ret = (char *)crypt(key, salt);
+
+	  	  if (ret == NULL)
+		 	 return 2;
+
+	  	  if (*(ret + 2) != '$')
+	  		 return 1;
+
+	  	  return 0;
+	     }
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+			   { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+			   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+			   { { echo "$as_me:$LINENO: error: Your system does not support MD5 passwords.  You must use the --disable-md5-passwords option" >&5
+echo "$as_me: error: Your system does not support MD5 passwords.  You must use the --disable-md5-passwords option" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+
       ;;
   *)
       { echo "$as_me:$LINENO: result: no" >&5
