Added initial FHS compliance
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/v5_5_0@860 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -676,8 +676,11 @@ EGREP
 LIBOBJS
 vpopuser
 vpopgroup
-vpopmaildir
-domains_dir
+VPOPMAIL_DIR_BIN
+VPOPMAIL_DIR_ETC
+VPOPMAIL_DIR_LIB
+VPOPMAIL_DIR_INCLUDE
+VPOPMAIL_DIR_DOMAINS
 acx_pthread_config
 PTHREAD_CC
 PTHREAD_LIBS
@@ -1269,7 +1272,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-non-root-build    Build vpopmail as a non-root user, only if you know what you are doing. see README.non-root
+  --disable-root-check    Disables root user check when compiling vpopmail
   --enable-qmaildir=DIR      Directory where qmail control and user directories are installed /var/qmail.
   --enable-qmail-newu=PATH   Full path to qmail-newu program.
   --enable-qmail-inject=PATH Full path to qmail-inject program.
@@ -1297,9 +1300,6 @@ Optional Features:
   --enable-maildrop          Enable maildrop. See  README.maildrop for more info.
   --enable-maildrop-prog=PATH    Full path to maildrop program /usr/{local/}bin/maildrop.
   --disable-domainquotas      Disable non-system domain quotas. See README.quotas for more info.
-  --enable-domains-dir=TEXT  Directory in ~vpopmail to store domains (default=domains).
-  --enable-incdir=DIR        Your MySQL/Oracle 'include' directory.
-  --enable-libdir=DIR        Your MySQL/Oracle 'lib' directory.
   --enable-passwd            Enable /etc/passwd (or shadow) accounts in addition to virtual domains.
   --enable-logging=OPT       Log to syslog: n=nothing, e=errors only (default), y=all attempts, p=errors with passwords, v=verbose (all attempts, with passwords).
   --enable-log-name=TEXT     Set syslog name vpopmail.
@@ -6352,7 +6352,7 @@ echo $ECHO_N "checking if we're building on Solaris... $ECHO_C" >&6; }
 
 case "$host" in
   *-*-solaris*)
-    extralibflags="-R$libdir -lm -lnsl -lsocket"
+    extralibflags="-lm -lnsl -lsocket"
 	{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 
@@ -6583,9 +6583,13 @@ esac
 
 #----------------------------------------------------------------------
 
-# Check whether --enable-non-root-build was given.
-if test "${enable_non_root_build+set}" = set; then
-  enableval=$enable_non_root_build; idtest='false'
+#
+# FHS compliance
+#
+
+# Check whether --enable-root-check was given.
+if test "${enable_root_check+set}" = set; then
+  enableval=$enable_root_check; idtest='false'
 else
   idtest='true'
 fi
@@ -6597,10 +6601,10 @@ if $idtest && test `$idcommand` != "0"
 then
   { echo "$as_me:$LINENO: WARNING: === vpopmail must be configured as root. ===" >&5
 echo "$as_me: WARNING: === vpopmail must be configured as root. ===" >&2;}
-  { echo "$as_me:$LINENO: WARNING: === please switch to the root user and  ===" >&5
-echo "$as_me: WARNING: === please switch to the root user and  ===" >&2;}
-  { echo "$as_me:$LINENO: WARNING: === run ./configure. Thanks ===" >&5
-echo "$as_me: WARNING: === run ./configure. Thanks ===" >&2;}
+  { echo "$as_me:$LINENO: WARNING: === please switch to the root user and   ===" >&5
+echo "$as_me: WARNING: === please switch to the root user and   ===" >&2;}
+  { echo "$as_me:$LINENO: WARNING: === run ./configure.                     ===" >&5
+echo "$as_me: WARNING: === run ./configure.                     ===" >&2;}
   { { echo "$as_me:$LINENO: error: aborted." >&5
 echo "$as_me: error: aborted." >&2;}
    { (exit 1); exit 1; }; }
@@ -6976,14 +6980,85 @@ echo "$as_me: error: No vpopmail home directory" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+#
+# Determine directories
+#
+
+{ echo "$as_me:$LINENO: checking directory layout" >&5
+echo $ECHO_N "checking directory layout... $ECHO_C" >&6; }
+
 vpopmaildir=`cat vpopmail.dir`
+rm -f vpopmail.dir
+
+if test "$prefix" = "NONE"
+then
+   { echo "$as_me:$LINENO: result: vpopmail style" >&5
+echo "${ECHO_T}vpopmail style" >&6; }
+   prefix=$vpopmaildir
+   prefix=$vpopmaildir
+
+   localstatedir=$prefix"/domains"
+   localstatedir=$localstatedir
+
+else
+   { echo "$as_me:$LINENO: result: FHS" >&5
+echo "${ECHO_T}FHS" >&6; }
+   eval localstatedir=$localstatedir"/vpopmail"
+   eval sysconfdir=$sysconfdir"/vpopmail"
+   eval includedir=$includedir"/vpopmail"
+fi
+
+#if test "$exec_prefix" = "NONE"
+#then
+#   eval exec_prefix=$prefix
+#fi
+
+eval vpopmail_dir_bin=$bindir
+eval vpopmail_dir_etc=$sysconfdir
+eval vpopmail_dir_lib=$libdir
+eval vpopmail_dir_domains=$localstatedir
+eval vpopmail_dir_include=$includedir
 
 
 cat >>confdefs.h <<_ACEOF
-#define VPOPMAILDIR "$vpopmaildir"
+#define VPOPMAIL_DIR_BIN "$vpopmail_dir_bin"
 _ACEOF
 
-rm -f vpopmail.dir
+
+cat >>confdefs.h <<_ACEOF
+#define VPOPMAIL_DIR_ETC "$vpopmail_dir_etc"
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define VPOPMAIL_DIR_LIB "$vpopmail_dir_lib"
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define VPOPMAIL_DIR_INCLUDE "$vpopmail_dir_include"
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define VPOPMAIL_DIR_DOMAINS "$vpopmail_dir_domains"
+_ACEOF
+
+
+VPOPMAIL_DIR_BIN=$vpopmail_dir_bin
+
+VPOPMAIL_DIR_ETC=$vpopmail_dir_etc
+
+VPOPMAIL_DIR_LIB=$vpopmail_dir_lib
+
+VPOPMAIL_DIR_INCLUDE=$vpopmail_dir_include
+
+VPOPMAIL_DIR_DOMAINS=$vpopmail_dir_domains
+
+
+#
+# UID:GID
+#
 
 vpopmailuid=`cat vpopmail.uid`
 
@@ -7002,25 +7077,25 @@ _ACEOF
 rm -f vpopmail.gid
 rm -f vpopusername
 
-#----------------------------------------------------------------------
+#
+# Create etc directory if root
+#
 
-if test ! -d $vpopmaildir/etc
+if test ! -d $vpopmail_etc_dir
 then
-  if test ! -d $vpopmaildir
-  then
-    { echo "$as_me:$LINENO: WARNING: creating $vpopmaildir " >&5
-echo "$as_me: WARNING: creating $vpopmaildir " >&2;}
-    mkdir -p $vpopmaildir
-    chown $vpopmailuid $vpopmaildir
-    chgrp $vpopmailgid $vpopmaildir
-    chmod 755 $vpopmaildir
-  fi
-  { echo "$as_me:$LINENO: WARNING: making a vpopmail etc directory " >&5
-echo "$as_me: WARNING: making a vpopmail etc directory " >&2;}
-  mkdir $vpopmaildir/etc
-  chown $vpopmailuid "$vpopmaildir"/etc
-  chgrp $vpopmailgid "$vpopmaildir"/etc
-  chmod 755 "$vpopmaildir"/etc
+   if test ! $idtest
+   then
+	  { echo "$as_me:$LINENO: WARNING: $vpopmail_dir_etc does not exist!" >&5
+echo "$as_me: WARNING: $vpopmail_dir_etc does not exist!" >&2;}
+	  sleep 3
+   else
+	  { echo "$as_me:$LINENO: WARNING: making vpopmail etc directory" >&5
+echo "$as_me: WARNING: making vpopmail etc directory" >&2;}
+	  mkdir -p $vpopmail_dir_etc
+	  chown $vpopmailuid $vpopmail_dir_etc
+	  chgrp $vpopmailgid $vpopmail_dir_etc
+	  chmod 755 $vpopmail_dir_etc
+   fi
 fi
 
 #----------------------------------------------------------------------
@@ -7099,7 +7174,7 @@ _ACEOF
     { echo "$as_me:$LINENO: checking whether we can locate the tcp.smtp file" >&5
 echo $ECHO_N "checking whether we can locate the tcp.smtp file... $ECHO_C" >&6; }
     tcpserver_file=""
-    for f in "$vpopmaildir"/etc/tcp.smtp /etc/tcp.smtp /etc/tcprules.d/qmail-smtpd
+    for f in "$sysconfdir"/tcp.smtp /etc/tcp.smtp /etc/tcprules.d/qmail-smtpd
     do
         if test -f $f
         then
@@ -7117,11 +7192,11 @@ else
             then
                 { echo "$as_me:$LINENO: WARNING: Unable to find your tcpserver relay file." >&5
 echo "$as_me: WARNING: Unable to find your tcpserver relay file." >&2;}
-                { echo "$as_me:$LINENO: WARNING: Creating tcp.smtp in \"$vpopmaildir\"/etc/tcp.smtp." >&5
-echo "$as_me: WARNING: Creating tcp.smtp in \"$vpopmaildir\"/etc/tcp.smtp." >&2;}
+                { echo "$as_me:$LINENO: WARNING: Creating tcp.smtp in \"$sysconfdir\"/tcp.smtp." >&5
+echo "$as_me: WARNING: Creating tcp.smtp in \"$sysconfdir\"/tcp.smtp." >&2;}
 
-                echo "127.:allow,RELAYCLIENT=\"\"" > "$vpopmaildir"/etc/tcp.smtp
-                tcpserver_file="$vpopmaildir"/etc/tcp.smtp
+                echo "127.:allow,RELAYCLIENT=\"\"" > "$sysconfdir"/tcp.smtp
+                tcpserver_file="$sysconfdir"/tcp.smtp
             fi
 
 
@@ -7189,9 +7264,9 @@ _ACEOF
 
 
 
-    open_smtp_cur="$vpopmaildir/etc/open-smtp"
-    open_smtp_tmp="$vpopmaildir/etc/open-smtp.tmp"
-    open_smtp_lok="$vpopmaildir/etc/open-smtp.lock"
+    open_smtp_cur="$sysconfdir/open-smtp"
+    open_smtp_tmp="$sysconfdir/open-smtp.tmp"
+    open_smtp_lok="$sysconfdir/open-smtp.lock"
 
 cat >>confdefs.h <<_ACEOF
 #define OPEN_SMTP_CUR_FILE "$open_smtp_cur"
@@ -7839,7 +7914,7 @@ esac
 
 #----------------------------------------------------------------------
 
-vlimits_default="$vpopmaildir/etc/vlimits.default"
+eval vlimits_default="$sysconfdir/vlimits.default"
 
 
 cat >>confdefs.h <<_ACEOF
@@ -7849,55 +7924,15 @@ _ACEOF
 
 #----------------------------------------------------------------------
 
-domains_dir="domains"
+#domains_dir="domains"
 
-# Check whether --enable-domains-dir was given.
-if test "${enable_domains_dir+set}" = set; then
-  enableval=$enable_domains_dir; domains_dir="$enableval"
-fi
+#AC_ARG_ENABLE(domains-dir,
+#    [  --enable-domains-dir=TEXT  Directory in ~vpopmail to store domains (default=domains).],
+#    domains_dir="$enableval",
+#)
 
-
-
-cat >>confdefs.h <<_ACEOF
-#define DOMAINS_DIR "$domains_dir"
-_ACEOF
-
-
-
-#----------------------------------------------------------------------
-
-# cant contain this following block in the mysql section, as it is also used by oracle
-incdir=""
-for f in /usr/local/mysql/include/mysql /usr/local/mysql/include /usr/local/include/mysql /usr/include/mysql
-do
-    if test -d $f
-    then
-        incdir=$f
-        break
-    fi
-done
-
-# Check whether --enable-incdir was given.
-if test "${enable_incdir+set}" = set; then
-  enableval=$enable_incdir; incdir="$enableval"
-fi
-
-
-libdir=""
-for f in /usr/local/mysql/lib/mysql /usr/local/mysql/lib  /usr/local/lib/mysql /usr/lib/mysql
-do
-    if test -d $f
-    then
-        libdir=$f
-        break
-    fi
-done
-
-# Check whether --enable-libdir was given.
-if test "${enable_libdir+set}" = set; then
-  enableval=$enable_libdir; libdir="$enableval"
-fi
-
+#AC_DEFINE_UNQUOTED(DOMAINS_DIR,"$domains_dir","")
+#AC_SUBST(domains_dir)
 
 #----------------------------------------------------------------------
 
@@ -9241,6 +9276,20 @@ echo "$as_me: error: --enable-default-domain has been superceded. The default do
 fi
 
 
+# Check whether --enable-non-root-build was given.
+if test "${enable_non_root_build+set}" = set; then
+  enableval=$enable_non_root_build;
+	  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	  { { echo "$as_me:$LINENO: error: --enable-non-root-build is deprecated.  Please use --disable-root-check" >&5
+echo "$as_me: error: --enable-non-root-build is deprecated.  Please use --disable-root-check" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi
+
+
+
 { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 
@@ -9930,8 +9979,11 @@ EGREP!$EGREP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 vpopuser!$vpopuser$ac_delim
 vpopgroup!$vpopgroup$ac_delim
-vpopmaildir!$vpopmaildir$ac_delim
-domains_dir!$domains_dir$ac_delim
+VPOPMAIL_DIR_BIN!$VPOPMAIL_DIR_BIN$ac_delim
+VPOPMAIL_DIR_ETC!$VPOPMAIL_DIR_ETC$ac_delim
+VPOPMAIL_DIR_LIB!$VPOPMAIL_DIR_LIB$ac_delim
+VPOPMAIL_DIR_INCLUDE!$VPOPMAIL_DIR_INCLUDE$ac_delim
+VPOPMAIL_DIR_DOMAINS!$VPOPMAIL_DIR_DOMAINS$ac_delim
 acx_pthread_config!$acx_pthread_config$ac_delim
 PTHREAD_CC!$PTHREAD_CC$ac_delim
 PTHREAD_LIBS!$PTHREAD_LIBS$ac_delim
@@ -9941,7 +9993,7 @@ VUSAGEDLIBS!$VUSAGEDLIBS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 75; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -10379,8 +10431,11 @@ echo "           $PACKAGE_NAME $PACKAGE_VERSION"
 echo "            Current settings"
 echo "---------------------------------------"
 echo ""
-echo "vpopmail directory = "$vpopmaildir""
-echo " domains directory = "$vpopmaildir"/"$domains_dir""
+echo " domains directory = "$vpopmail_dir_domains""
+echo "    conf directory = $vpopmail_dir_etc"
+echo "     bin directory = $vpopmail_dir_bin"
+echo "     lib directory = $vpopmail_dir_lib"
+echo " include directory = $vpopmail_dir_include"
 echo "               uid = "$vpopmailuid""
 echo "               gid = "$vpopmailgid""
 
