Updated to report failure finding LDAP libraries
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/v5_5_0@888 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/backends/ldap/configure b/backends/ldap/configure
--- a/backends/ldap/configure
+++ b/backends/ldap/configure
@@ -2964,6 +2964,10 @@ _ACEOF
 
   LIBS="-lldap $LIBS"
 
+else
+   { { echo "$as_me:$LINENO: error: Can't locate LDAP libraries.  Please use --enable-libdir=/path to specify location." >&5
+echo "$as_me: error: Can't locate LDAP libraries.  Please use --enable-libdir=/path to specify location." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
@@ -3035,6 +3039,10 @@ _ACEOF
 
   LIBS="-llber $LIBS"
 
+else
+   { { echo "$as_me:$LINENO: error: Can't locate LDAP libraries.  Please use --enable-libdir=/path to specify location." >&5
+echo "$as_me: error: Can't locate LDAP libraries.  Please use --enable-libdir=/path to specify location." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
