remove enable-domainquotas option until the domain quota code is fixed
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/stable-5_4@432 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/vpopmail/configure b/vpopmail/configure
--- a/vpopmail/configure
+++ b/vpopmail/configure
@@ -855,7 +855,6 @@ Optional Features:
   --enable-sqwebmail-pass    Store a copy of the user's password in the the user's maildir for use by pre-v3 sqwebmail.
   --enable-qmail-ext         Enable qmail email address extension support.
   --enable-ip-alias-domains  Enable mapping of default domain via reverse ip lookup table.
-  --enable-domainquotas      Enable non-system domain quotas. See README.quotas for more info.
   --enable-domains-dir=TEXT  Set domains directory name for ~vpopmail/domains/user/.
   --enable-incdir=DIR        Your MySQL/Oracle 'include' directory.
   --enable-libdir=DIR        Your MySQL/Oracle 'lib' directory.
@@ -5732,36 +5731,26 @@ echo "${ECHO_T}no" >&6
 esac
 
 #----------------------------------------------------------------------
-
-echo "$as_me:$LINENO: checking whether domainquotas is enabled" >&5
-echo $ECHO_N "checking whether domainquotas is enabled... $ECHO_C" >&6
-# Check whether --enable-domainquotas or --disable-domainquotas was given.
-if test "${enable_domainquotas+set}" = set; then
-  enableval="$enable_domainquotas"
-  ENABLE_DOMAIN_QUOTAS=$enableval
-else
-
-                        ENABLE_DOMAIN_QUOTAS=0
-
-
-fi;
-
-case $ENABLE_DOMAIN_QUOTAS in
-  0*|n*|N*)
-      echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-      ;;
-  *)
-      echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-      ENABLE_DOMAIN_QUOTAS=1
-
-cat >>confdefs.h <<_ACEOF
-#define DOMAIN_QUOTAS $ENABLE_DOMAIN_QUOTAS
-_ACEOF
-
-      ;;
-esac
+#  -- domain quotas disabled until they actually work again --
+#AC_MSG_CHECKING(whether domainquotas is enabled)
+#AC_ARG_ENABLE(domainquotas,
+#        [  --enable-domainquotas      Enable non-system domain quotas. See README.quotas for more info.],
+#        ENABLE_DOMAIN_QUOTAS=$enableval,
+#                [
+#                        ENABLE_DOMAIN_QUOTAS=0
+#                ]
+#)
+#
+#case $ENABLE_DOMAIN_QUOTAS in
+#  0*|n*|N*)
+#      AC_MSG_RESULT(no)
+#      ;;
+#  *)
+#      AC_MSG_RESULT(yes)
+#      ENABLE_DOMAIN_QUOTAS=1
+#      AC_DEFINE_UNQUOTED(DOMAIN_QUOTAS,$ENABLE_DOMAIN_QUOTAS,"")
+#      ;;
+#esac
 
 #----------------------------------------------------------------------
 
@@ -6756,6 +6745,19 @@ if test "${enable_active_directory+set}" = set; then
 echo "${ECHO_T}yes" >&6
         { { echo "$as_me:$LINENO: error: --enable-active-directory has been superceded. Please use --enable-auth-module=activedir instead" >&5
 echo "$as_me: error: --enable-active-directory has been superceded. Please use --enable-auth-module=activedir instead" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi;
+
+# Check whether --enable-domainquotas or --disable-domainquotas was given.
+if test "${enable_domainquotas+set}" = set; then
+  enableval="$enable_domainquotas"
+
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        { { echo "$as_me:$LINENO: error: --enable-domainquotas has been temporarily disabled since the domain quota code is broken." >&5
+echo "$as_me: error: --enable-domainquotas has been temporarily disabled since the domain quota code is broken." >&2;}
    { (exit 1); exit 1; }; }
 
 
@@ -8153,14 +8155,14 @@ case $IPALIAS in
 esac
 
 
-case $ENABLE_DOMAIN_QUOTAS in
-  1*|y*|Y*)
-    echo "     domain quotas = ON  --enable-domainquotas"
-    ;;
-  *)
-    echo "     domain quotas = OFF --disable-domainquotas (default)"
-    ;;
-esac
+#case $ENABLE_DOMAIN_QUOTAS in
+#  1*|y*|Y*)
+#    echo "     domain quotas = ON  --enable-domainquotas"
+#    ;;
+#  *)
+#    echo "     domain quotas = OFF --disable-domainquotas (default)"
+#    ;;
+#esac
 
 
 case $AUTH_MODULE in
