Changes related to SQL logging on MySQL and PostgreSQL
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/stable-5_4@385 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/vpopmail/configure b/vpopmail/configure
--- a/vpopmail/configure
+++ b/vpopmail/configure
@@ -864,8 +864,7 @@ Optional Features:
   --enable-logging=OPT       Log to syslog: n=nothing, e=errors only (default), y=all attempts, p=errors with passwords, v=verbose (all attempts, with passwords).
   --enable-log-name=TEXT     Set syslog name vpopmail.
   --disable-auth-logging     Don't record time and ip of last auth attempt. Valid only for CDB, MySQL, PGSQL, LDAP, ActiveDir.
-  --enable-mysql-logging     Enable authentication logging to MySQL.  Uses setting from --enable-auth-logging.
-  --enable-pgsql-logging     Enable authentication logging to PostgreSQL.  Uses setting from --enable-auth-logging.
+  --enable-sql-logging       Enable authentication logging to MySQL/Postgres.
   --enable-mysql-limits      Use MySQL to store limits instead of .qmailadmin-limits files.
   --enable-mysql-replication Enable support for replicated MySQL auth servers.
   --enable-valias            Store email aliases in MySQL.
@@ -6461,72 +6460,33 @@ esac
 
 #----------------------------------------------------------------------
 
-echo "$as_me:$LINENO: checking whether mysql-logging is enabled" >&5
-echo $ECHO_N "checking whether mysql-logging is enabled... $ECHO_C" >&6
-# Check whether --enable-mysql-logging or --disable-mysql-logging was given.
-if test "${enable_mysql_logging+set}" = set; then
-  enableval="$enable_mysql_logging"
-  ENABLE_MYSQL_LOGGING=$enableval
+echo "$as_me:$LINENO: checking whether sql-logging is enabled" >&5
+echo $ECHO_N "checking whether sql-logging is enabled... $ECHO_C" >&6
+# Check whether --enable-sql-logging or --disable-sql-logging was given.
+if test "${enable_sql_logging+set}" = set; then
+  enableval="$enable_sql_logging"
+  ENABLE_SQL_LOGGING=$enableval
 else
 
-                        ENABLE_MYSQL_LOGGING=n
+                        ENABLE_SQL_LOGGING=n
 
 
 fi;
 
-case $ENABLE_MYSQL_LOGGING in
+case $ENABLE_SQL_LOGGING in
   1*|y*|Y*)
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-      if test $USE_MYSQL != 1
+      if test $USE_SQL != 1
       then
-          { { echo "$as_me:$LINENO: error: mysql-logging is only supported in the MySQL authentication module" >&5
-echo "$as_me: error: mysql-logging is only supported in the MySQL authentication module" >&2;}
+          { { echo "$as_me:$LINENO: error: sql-logging is only supported in the MySQL/Postgres authentication module" >&5
+echo "$as_me: error: sql-logging is only supported in the MySQL/Postgres authentication module" >&2;}
    { (exit 1); exit 1; }; }
       else
-        ENABLE_MYSQL_LOGGING=1
+        ENABLE_SQL_LOGGING=1
 
 cat >>confdefs.h <<_ACEOF
-#define ENABLE_MYSQL_LOGGING $ENABLE_MYSQL_LOGGING
-_ACEOF
-
-      fi
-      ;;
-  *)
-      echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-      ;;
-esac
-
-#----------------------------------------------------------------------
-
-echo "$as_me:$LINENO: checking whether pgsql-logging is enabled" >&5
-echo $ECHO_N "checking whether pgsql-logging is enabled... $ECHO_C" >&6
-# Check whether --enable-pgsql-logging or --disable-pgsql-logging was given.
-if test "${enable_pgsql_logging+set}" = set; then
-  enableval="$enable_pgsql_logging"
-  ENABLE_PGSQL_LOGGING=$enableval
-else
-
-                        ENABLE_PGSQL_LOGGING=n
-
-
-fi;
-
-case $ENABLE_PGSQL_LOGGING in
-  1*|y*|Y*)
-      echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-      if test $USE_PGSQL != 1
-      then
-          { { echo "$as_me:$LINENO: error: pgsql-logging is only supported in the PostgreSQL authentication module" >&5
-echo "$as_me: error: pgsql-logging is only supported in the PostgreSQL authentication module" >&2;}
-   { (exit 1); exit 1; }; }
-      else
-          ENABLE_PGSQL_LOGGING=1
-
-cat >>confdefs.h <<_ACEOF
-#define ENABLE_PGSQL_LOGGING $ENABLE_PGSQL_LOGGING
+#define ENABLE_SQL_LOGGING $ENABLE_SQL_LOGGING
 _ACEOF
 
       fi
@@ -6696,6 +6656,32 @@ esac
 
 echo "$as_me:$LINENO: checking whether any discontinued --enable commands have been used" >&5
 echo $ECHO_N "checking whether any discontinued --enable commands have been used... $ECHO_C" >&6
+
+# Check whether --enable-mysql-logging or --disable-mysql-logging was given.
+if test "${enable_mysql_logging+set}" = set; then
+  enableval="$enable_mysql_logging"
+
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        { { echo "$as_me:$LINENO: error: --enable-mysql-logging has been superceded.  Please use --enable-sql-logging instead" >&5
+echo "$as_me: error: --enable-mysql-logging has been superceded.  Please use --enable-sql-logging instead" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi;
+
+# Check whether --enable-pgsql-logging or --disable-pgsql-logging was given.
+if test "${enable_pgsql_logging+set}" = set; then
+  enableval="$enable_pgsql_logging"
+
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        { { echo "$as_me:$LINENO: error: --enable-pgsql-logging has been superceded.  Please use --enable-sql-logging instead" >&5
+echo "$as_me: error: --enable-pgsql-logging has been superceded.  Please use --enable-sql-logging instead" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi;
 
 # Check whether --enable-mysql or --disable-mysql was given.
 if test "${enable_mysql+set}" = set; then
@@ -8194,12 +8180,12 @@ case $AUTH_MODULE in
         ;;
     esac
 
-    case $ENABLE_MYSQL_LOGGING in
+    case $ENABLE_SQL_LOGGING in
       1*|y*|Y*)
-        echo "     mysql logging = ON  --enable-mysql-logging"
+        echo "       sql logging = ON  --enable-sql-logging"
         ;;
       *)
-        echo "     mysql logging = OFF --disable-mysql-logging (default)"
+        echo "       sql logging = OFF --disable-sql-logging (default)"
         ;;
     esac
 
@@ -8225,12 +8211,12 @@ case $AUTH_MODULE in
   pg*|Pg*|PG*)
     echo "       auth module = postgres --enable-auth-module=postgres"
 
-    case $ENABLE_PGSQL_LOGGING in
+    case $ENABLE_SQL_LOGGING in
       1*|y*|Y*)
-        echo "     pgsql logging = ON  --enable-pgsql-logging"
+        echo "       sql logging = ON  --enable-sql-logging"
         ;;
       *)
-        echo "     pgsql logging = OFF --disable-pgsql-logging (default)"
+        echo "       sql logging = OFF --disable-sql-logging (default)"
       ;;
     esac
     ;;
