revert valias patch
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/stable-5_4@555 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/vpopmail/configure b/vpopmail/configure
--- a/vpopmail/configure
+++ b/vpopmail/configure
@@ -6578,19 +6578,19 @@ case $VALIAS in
   1*|y*|Y*)
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-#        if test "$USE_SQL" != 1
-#        then
-#                { { echo "$as_me:$LINENO: error: valias option is only supported in the SQL authentication modules" >&5
-#echo "$as_me: error: valias option is only supported in the SQL authentication modules" >&2;}
-#   { (exit 1); exit 1; }; }
-#        else
+        if test "$USE_SQL" != 1
+        then
+                { { echo "$as_me:$LINENO: error: valias option is only supported in the SQL authentication modules" >&5
+echo "$as_me: error: valias option is only supported in the SQL authentication modules" >&2;}
+   { (exit 1); exit 1; }; }
+        else
                 VALIAS=1
 
 cat >>confdefs.h <<_ACEOF
 #define VALIAS $VALIAS
 _ACEOF
 
-#        fi
+        fi
         ;;
   *)
         echo "$as_me:$LINENO: result: no" >&5
