Update configure with correct location of vlimits.default
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/trunk@223 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/vpopmail/configure b/vpopmail/configure
--- a/vpopmail/configure
+++ b/vpopmail/configure
@@ -7176,8 +7176,8 @@ if test "${enable_hardquota+set}" = set; then
 
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-        { { echo "$as_me:$LINENO: error: --enable-hardquota has been superceded. Please use the ~vpopmail/vlimits.default file instead." >&5
-echo "$as_me: error: --enable-hardquota has been superceded. Please use the ~vpopmail/vlimits.default file instead." >&2;}
+        { { echo "$as_me:$LINENO: error: --enable-hardquota has been superceded. Please use the ~vpopmail/etc/vlimits.default file instead." >&5
+echo "$as_me: error: --enable-hardquota has been superceded. Please use the ~vpopmail/etc/vlimits.default file instead." >&2;}
    { (exit 1); exit 1; }; }
 
 
@@ -7189,8 +7189,8 @@ if test "${enable_defaultquota+set}" = set; then
 
         echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-        { { echo "$as_me:$LINENO: error: --enable-defaultquota has been superceded. Please use the ~vpopmail/vlimits.default file instead." >&5
-echo "$as_me: error: --enable-defaultquota has been superceded. Please use the ~vpopmail/vlimits.default file instead." >&2;}
+        { { echo "$as_me:$LINENO: error: --enable-defaultquota has been superceded. Please use the ~vpopmail/etc/vlimits.default file instead." >&5
+echo "$as_me: error: --enable-defaultquota has been superceded. Please use the ~vpopmail/etc/vlimits.default file instead." >&2;}
    { (exit 1); exit 1; }; }
 
 
