Updated to check if MySQL library not found
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/branches/v5_5_0@887 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/backends/mysql/configure b/backends/mysql/configure
--- a/backends/mysql/configure
+++ b/backends/mysql/configure
@@ -3106,6 +3106,10 @@ _ACEOF
 
   LIBS="-lmysqlclient $LIBS"
 
+else
+   { { echo "$as_me:$LINENO: error: Can't find MySQL library.  Please use --enable-libdir=/path to specifcy location." >&5
+echo "$as_me: error: Can't find MySQL library.  Please use --enable-libdir=/path to specifcy location." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
