Updated some defaults
git-svn-id: https://svn.code.sf.net/p/vpopmail/code/trunk@978 8f0cf6e2-dddb-4e5e-b901-7f5e1d474549

diff --git a/vusaged/contrib/rc.vusaged.in b/vusaged/contrib/rc.vusaged.in
--- a/vusaged/contrib/rc.vusaged.in
+++ b/vusaged/contrib/rc.vusaged.in
@@ -11,11 +11,14 @@
 #
 
 PIDFILE=/var/run/vusaged.pid
-VUSAGED=@vpopmaildir@/bin/vusaged
+VUSAGED=@VPOPMAIL_DIR_BIN@/vusaged
+WORKINGDIR=@VPOPMAIL_DIR_ETC@
 
 case "$1" in
    start)
 	  echo -n "Starting vusaged: "
+
+	  cd $WORKINGDIR || (echo "cannot change to $WORKINGDIR"; exit 1)
 
 	  if [ -e $PIDFILE ]; then
 		 echo "already running or stale pidfile $PIDFILE"
